### PR TITLE
Wrap migration in a transaction

### PR DESCRIPTION
**Pull request by evanwhalen**
@prsimp @HoyaBoya this should do the trick by using `ActiveRecord::Migrator.up` or  `ActiveRecord::Migrator.down` instead of  `ActiveRecord::Migrator.run` in rake tasks where we want to wrap migrations in transactions. Here are the fixed rake tasks:
* `rake db:migrate:with_data`
* `rake db:rollback:with_data`
* `rake db:forward:with_data`
* `rake data:forward`

### CODE REVIEW

**Comment by HoyaBoya** [comment]
This makes sense.

Do we want to create ```rails3``` and ```rails4``` branches instead of our ```master``` and ```blueapron``` distinction? Then we can target this PR into rails3, and have master track the author's master?

**Comment by evanwhalen** [comment]
@HoyaBoya I'm up for whatever we think is the best strategy for maintaining this. Do we follow a similar strategy with other gems we've forked?

**Comment by evanwhalen** [comment]
The strategy you suggest seems sound to me

**Comment by prsimp** [comment]
Yeah I like to avoid pushing commits to branches that exist upstream (i.e. `master`) as it makes life easier when pulling in upstream changes.

Also, a quick glance indicates that the changes on the `blueapron` branch to make it Rails 4.1+ compatible are also compatible with 3.2, so we could probably push all the changes into one branch if we wanted.

**Comment by HoyaBoya** [comment]
The only reference I have is our Spree work.

https://github.com/blueapron/spree

There, I actually deleted master and we just have branches of what we were doing to against Spree's equivalent version.

Not that we have any new Rails projects coming down the pipe, but I'd imagine if we did, a developer would just grab our version ```master```, wonder WTF did BA fork this if there are no deltas, and not realize our work is on the side for Rails 4. That was my first impression when looking at the repo.

So yah, let's rename master to rails3, rename blueapron to rails4, and make it clear what we're doing is targeted to various Rails versions?

This is non-blocking. Feel free to merge this into master. :+1: then we can rename.

**Comment by evanwhalen** [comment]
@HoyaBoya and @prsimp I've closed this and opened a new PR to rails3

**Pull request closed without merging**
